### ISSUE TITLE
Seems some items are in moderation that shouldn’t be

### ISSUE THREAD

**Issue by kkirsche** [Trinityyi/can-my-dog-eat#3]
![image](https://user-images.githubusercontent.com/947110/117215251-fb3d5880-adcb-11eb-8e9a-61a26b8ee20e.jpg)

from my vet, you have avocados which are in moderation but that doesn’t align with what my vet has told us in person. I’ve attached the magnet they use as the basic high level guide.

**Comment by Trinityyi** [comment]
As stated in the website disclaimer, the website does not provide medical advice and is not intended to be a substitution for professional veterinarian advice. 
The truth is that due to avocado's high fat content, large quantities could indeed cause vomiting and diarrhea. This is also true for humans. Moreover, keep in mind that fruits aren't a necessary part of any dog's diet and there is always a possibility of diarrhea and your dog's stomach may not fully agree.
Having said that I will review the food list, especially food that  is labeled as "In Moderation", and will make any necessary changes to calibrate controversial and edge cases.
